# 3. 분류 모델 적용 및 성능 평가

In [1]:
import numpy as np
import pandas as pd

In [6]:
num = int(input('몇번째 테스트? :'))
search = input("회사명?")

몇번째 테스트? :9
회사명?삼성전자

In [3]:
df = pd.read_csv('csv/self_labeled_data.csv',encoding='utf-8') # encoding='cp949'
df.tail()

,date,title,self_label,sentiment,label
552,2023-06-05 18:28,"['울산', '현대', ',', '임금', '인', '상', '·', '고용', '...",0,0.22,0
553,2023-06-05 16:30,"['현대차·이케아코리아,', '광명점', '서', '친환경차', '전시']",1,0.69,1
554,2023-06-06 12:37,"['‘커넥티드카’', '기술경쟁', '심화…5G-V2X', '한국', '이', '선도']",1,0.47,0
555,2023-06-06 10:25,"['""', '전기차', '로', '전국일주', '""', '싱가포르', '관광객', ...",1,0.58,1
556,2023-06-05 17:46,"['노란봉투법', '닮은꼴', ""'"", '현대차', '파업', '소송', ',', ...",0,0.46,0

In [4]:
from sklearn.model_selection import train_test_split

# X_train = np.expand_dims(samsung_train['sentiment'].values,axis=1)
# X_test =np.expand_dims(samsung_test['sentiment'].values,axis=1)
# y_train =np.expand_dims(samsung_train['label'].values,axis=1)
# y_test = np.expand_dims(samsung_test['label'].values,axis=1)
# print(y_train)

X = np.expand_dims(df['sentiment'].values,axis=1)
y = np.expand_dims(df['self_label'].values,axis=1)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=156)

In [5]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

# 결정트리, Random Forest, 로지스틱 회귀를 위한 사이킷런 Classifier 클래스 생성
dt_clf = DecisionTreeClassifier(random_state=11)
rf_clf = RandomForestClassifier(random_state=11)
lr_clf = LogisticRegression(solver='liblinear')

# DecisionTreeClassifier 학습/예측/평가
dt_clf.fit(X_train,y_train)
dt_pred = dt_clf.predict(X_test)
print(f'DecisionTreeClassifier 정확도: {accuracy_score(y_test,dt_pred)}')

# RandomForestClassifier 학습/예측/평가
rf_clf.fit(X_train,y_train)
rf_pred = rf_clf.predict(X_test)
print(f"RandomForestClassifier 정확도: {accuracy_score(y_test,rf_pred)}")

# LogisticRegression 학습/예측/평가
lr_clf.fit(X_train,y_train)
lr_pred = lr_clf.predict(X_test)
print(f"LogisticRegression 정확도: {accuracy_score(y_test,lr_pred)}")

DecisionTreeClassifier 정확도: 0.8482142857142857
RandomForestClassifier 정확도: 0.8571428571428571
LogisticRegression 정확도: 0.8660714285714286

C:\Users\ahn\AppData\Local\Temp\ipykernel_11012\993524692.py:17: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  rf_clf.fit(X_train,y_train)
C:\Users\ahn\anaconda3\envs\CapstonStockProject\lib\site-packages\sklearn\utils\validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

In [10]:
new_df = pd.read_csv(f'csv/sentiment_{search}_{num}.csv')
new_df

,date,title,sentiment,label
0,2023-06-06 08:26:06,"['삼성전자', ',', '윈도', '운영체제', '탑재한', '키오스크', '신제...",0.44,0
1,2023-06-06 09:28:56,"['삼성전자', ',', '윈도우', '탑재한', ""'"", '삼성', ""키오스크'""...",0.29,0
2,2023-06-06 10:01:01,"['네이처', '에', '실리', 'ㄴ', '삼성전자', ""'"", '강유전체', ""...",0.48,0
3,2023-06-06 11:18:05,"['기재부', ',', '넥슨', '2대주주', '등극에…삼성家', '사례', '재...",0.33,0
4,2023-06-06 18:30:01,"['이건희', '가', '만들', 'ㄴ', ""'"", '품질', '의', ""삼성'…J...",0.32,0
5,2023-06-06 14:31:36,"['삼성家', '세', '모녀', ',', '상속세', '마련', '위하', '어'...",0.48,0
6,2023-06-06 13:09:19,"['애플', ',', 'MR', '헤드셋', '전격', '공개', '...', '메...",0.33,0
7,2023-06-06 11:47:01,"['“TSMC', '‘2나노', '반도체’', '시범생산', '착수…', '삼성',...",0.29,0
8,2023-06-06 19:20:06,"['""반도체·디스플레이·AI·바이오', '에', '투', '이', '자', '역량'...",0.31,0
9,2023-06-06 15:14:01,"['팀쿡', '의', '‘원', '모으', '아', '띵’', '은', '‘비전',...",0.48,0
10,2023-06-06 10:02:01,"['일본', '은', '어쩌다', '반도체', '추락', '국가', '가', '되'...",0.42,0
11,2023-06-06 11:20:00,"['삼성', '신경영', '30년', ',', '이제', '는', ""'"", '이재용...",0.41,0
12,2023-06-06 15:00:00,"['메타', '이', '이', '어', '애플·삼성', '도', '가', '세', ...",0.32,0
13,2023-06-06 11:10:00,"[""'"", '초일류', '삼성', ""'"", '을', '만들', 'ㄴ', '30년',...",0.39,0
14,2023-06-06 07:32:01,"['40년', '전', '삼성', '제안', '에', '뒤바뀌', 'ㄴ', ""운명…...",0.47,0
15,2023-06-06 16:52:01,"['“1만대', '모두', '완판입니다”', '망', '하', 'ㄴ', '줄', '...",0.26,0
16,2023-06-06 08:31:01,"['삼성·LG,', '""친환경', '라운지', '열', '고', ',', '흙공',...",0.41,0
17,2023-06-06 16:36:03,"['외국인', '은', '반도체', ""'"", '폭풍', ""매수'…개미"", '는', ...",0.44,0
18,2023-06-06 06:03:00,"['기업', ""'"", '지배구조', '핵심지표', ""'"", '준수율', '62%…S...",0.34,0
19,2023-06-06 14:01:01,"['RE100', '부담', '느끼', 'ㄴ', '기업들', ""'CF100"", '대...",0.64,1
20,2023-06-06 08:03:01,"['최태원·이재용', '회장', ',', '중국', '에', '슬그머니', '다니'...",0.42,0
21,2023-06-05 21:33:05,"['고공행진', '반도체…짙어지', '는', '온실가스']",0.38,0
22,2023-06-06 11:23:01,"['삼성', '신경영', '30년', ',', '이재용', '회장', '‘뉴', '...",0.45,0
23,2023-06-06 09:33:01,"['""', '올해', '만', '13조', ',', '폭풍', '매수', '""', ...",0.49,0
24,2023-06-06 12:06:01,"['""', '中', '추격', '하', '는', '신세지만""…삼성', '엑시노스,'...",0.40,0
25,2023-06-06 11:15:00,"[""'"", '신경영', '선언', ""'"", '30년', ',', '하', 'ㄴ', ...",0.28,0
26,2023-06-06 00:42:00,"['[', '글로벌', '아이', ']', '머스크', '방중', '이', '남기'...",0.53,1
27,2023-06-05 22:02:01,"['인텔', ',', '업계', '최초', '‘웨이퍼', '후', '이', '면서'...",0.33,0
28,2023-06-06 06:37:32,"['고공행진', '반도체…짙어지', '는', '온실가스']",0.38,0
29,2023-06-06 05:50:00,"['""', '매출', '20', '%', '가', '인건비', ',', '임금', ...",0.35,0
30,2023-06-06 18:00:01,"['""', '글로벌', 'TV', '사운드바', '트렌드', '는', '다다익선',...",0.43,0
31,2023-06-06 07:03:01,"['인기', '없', '던', '시골', '회사', '의', '대반전…주', '가'...",0.42,0
32,2023-06-06 16:36:11,"['수익률', '치솟', '자', '뭉칫돈', '몰리', '는', '반도체', 'E...",0.29,0
33,2023-06-06 16:48:06,"['“파운드리', '주도권', '탈환”', '인텔', '반격', '나', '아아다']",0.36,0

In [11]:
np.expand_dims(new_df['sentiment'].values,axis=1)
dt_pred_new = dt_clf.predict(np.expand_dims(new_df['sentiment'].values,axis=1))

rf_pred_new = rf_clf.predict(np.expand_dims(new_df['sentiment'].values,axis=1))

lr_pred_new = lr_clf.predict(np.expand_dims(new_df['sentiment'].values,axis=1))

In [13]:
print(dt_pred_new)
print(rf_pred_new)
print(lr_pred_new)

[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]

In [14]:
count_1 = 0
count_0 = 0
result = -1
for i in dt_pred:
    if i ==1:
        count_1 +=1
    else:
        count_0 +=1

if count_1 >= count_0:
    print("상승을 예측")
    result = 1
else:
    print("하락을 예측")
    result = 0

상승을 예측